In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# draw n random points drawn from [0, 1] and initialize the laplacian matrix
n=5
sample = np.random.uniform(size = (n, ))
ordered_list = np.sort(sample)
print(ordered_list)
laplacian = np.zeros((n, n))
for i in range(n-1):
    laplacian[i][i+1] = ordered_list[i] - ordered_list[i+1]
    laplacian[i+1][i] = ordered_list[i] - ordered_list[i+1]
for i in range(n):
    laplacian[i][i] = -np.sum(laplacian[i])
print(laplacian)

[0.00995667 0.06113948 0.10702112 0.40274124 0.50493035]
[[ 0.05118281 -0.05118281  0.          0.          0.        ]
 [-0.05118281  0.09706445 -0.04588164  0.          0.        ]
 [ 0.         -0.04588164  0.34160176 -0.29572012  0.        ]
 [ 0.          0.         -0.29572012  0.39790923 -0.10218911]
 [ 0.          0.          0.         -0.10218911  0.10218911]]


In [3]:
# cluster into k groups with a drift term delta
def drift_cluster(k, delta):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-3-2005fca8846d>, line 3)