In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# draw n random points drawn from [0, 1] and initialize the laplacian matrix
n=5
sample = np.random.uniform(size = (n, ))
ordered_list = np.sort(sample)
print(ordered_list)
laplacian = np.zeros((n, n))
for i in range(n-1):
    laplacian[i][i+1] = ordered_list[i] - ordered_list[i+1]
    laplacian[i+1][i] = ordered_list[i] - ordered_list[i+1]
for i in range(n):
    laplacian[i][i] = -np.sum(laplacian[i])
print(laplacian)

[0.29766446 0.41729896 0.60395542 0.60467499 0.69573504]
[[ 0.1196345  -0.1196345   0.          0.          0.        ]
 [-0.1196345   0.30629096 -0.18665646  0.          0.        ]
 [ 0.         -0.18665646  0.18737602 -0.00071957  0.        ]
 [ 0.          0.         -0.00071957  0.09177962 -0.09106006]
 [ 0.          0.          0.         -0.09106006  0.09106006]]


In [ ]:
# cluster into k groups with a drift term delta
def drift_cluster(k, delta):
    