In [19]:
from lib.spectral_clustering import spectral_clustering
from lib.categorical_similarity_functions import categorical_preprocessing_csv
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

First thing's first, we need to take our csv file and make it something that we can work with.

In [3]:
numOfAtts, data = categorical_preprocessing_csv("lib/data/mushrooms.csv")

Now, let's take that data and cluster it!

In [7]:
assns = spectral_clustering(data,2,"rw",numOfAtts=numOfAtts)

Please be a real thing:  [[1.         0.96085267 0.95796875 ... 0.9229095  0.94593881 0.92519783]
 [0.96085267 1.         0.99351086 ... 0.95104249 0.91610079 0.95333082]
 [0.95796875 0.99351086 1.         ... 0.95163808 0.91610079 0.95104249]
 ...
 [0.9229095  0.95104249 0.95163808 ... 1.         0.91495269 0.99606841]
 [0.94593881 0.91610079 0.91610079 ... 0.91495269 1.         0.91495269]
 [0.92519783 0.95333082 0.95104249 ... 0.99606841 0.91495269 1.        ]]


In [8]:
print(assns)

[1 0 0 ... 0 1 0]


Hooray! We have our assignments! Now, we need to be able to compare these assignments to the actual data (we want to see how well we clustered the data into poisonous and edible).

In [29]:
data = np.array(data.T)
verify = data[0] # @Max I called it verify because I want to verify the clusters
print(verify)
print(verify.shape)

['p' 'e' 'e' ... 'e' 'p' 'e']
(8124,)


Now that we have taken the first column and reshaped the data, we can convert our 'p''s to 1's and 'e''s to 0's so we can compare this vector to our assignments.

In [40]:
bindata = [] # @Max I called it bindata because i'm taking the data and converting it to 0's and 1's, like binary
for i in range(len(verify)):
    if verify[i]=='p':
        bindata.append(1)
    elif verify[i] == 'e':
        bindata.append(0)
bindata = np.array(bindata)
print(bindata)

[1 0 0 ... 0 1 0]


Now, we'll compute the error by taking the norm of the difference between the cluster assignments vector and the actual categorical assignments of the mushrooms.

In [47]:
errvec = assns-bindata # @Max I called it errvec because i'm going to use it to compute the error
n= error.shape[0]
err = np.linalg.norm(error)/n
print(err)

0.002892008893271967


This does pretty well! But it's also worth noting that we use the column that tells us whether a mushroom is poisonous or not to make our clusters. To get a more accurate representation of how well our clustering algorithm works, we should ignore this column when we cluster and then make the same comparison as we did here.